a = input('Ваш возраст ')
b = input('Ваш пол ')
c = input('Ваше имя ')
d = input('Город где вы живете ')
e = input('В каком классе учитесь ')
x = []
x.append(a)
x.append(b)
x.append(c)
x.append(d)
x.append(e)
print (x)